//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCuratorRollout) DeepCopyInto(out *ClusterCuratorRollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCuratorRollout.
func (in *ClusterCuratorRollout) DeepCopy() *ClusterCuratorRollout {
	if in == nil {
		return nil
	}
	out := new(ClusterCuratorRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCuratorRollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCuratorRolloutList) DeepCopyInto(out *ClusterCuratorRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterCuratorRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCuratorRolloutList.
func (in *ClusterCuratorRolloutList) DeepCopy() *ClusterCuratorRolloutList {
	if in == nil {
		return nil
	}
	out := new(ClusterCuratorRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCuratorRolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCuratorRolloutSpec) DeepCopyInto(out *ClusterCuratorRolloutSpec) {
	*out = *in
	if in.OnlyUpgradeFromOpenShiftVersions != nil {
		in, out := &in.OnlyUpgradeFromOpenShiftVersions, &out.OnlyUpgradeFromOpenShiftVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.SelectionSpec.DeepCopyInto(&out.SelectionSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCuratorRolloutSpec.
func (in *ClusterCuratorRolloutSpec) DeepCopy() *ClusterCuratorRolloutSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCuratorRolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCuratorRolloutStatus) DeepCopyInto(out *ClusterCuratorRolloutStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.LastReconcileDuration != nil {
		in, out := &in.LastReconcileDuration, &out.LastReconcileDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Placements != nil {
		in, out := &in.Placements, &out.Placements
		*out = make([]PlacementStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TotalCounts != nil {
		in, out := &in.TotalCounts, &out.TotalCounts
		*out = new(StateCounts)
		**out = **in
	}
	if in.FailedClusters != nil {
		in, out := &in.FailedClusters, &out.FailedClusters
		*out = make([]FailedClusterInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InProgressClusters != nil {
		in, out := &in.InProgressClusters, &out.InProgressClusters
		*out = make([]InProgressClusterInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SoakStatus != nil {
		in, out := &in.SoakStatus, &out.SoakStatus
		*out = new(SoakStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.RolloutPlan != nil {
		in, out := &in.RolloutPlan, &out.RolloutPlan
		*out = make([]RolloutStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentStepIndex != nil {
		in, out := &in.CurrentStepIndex, &out.CurrentStepIndex
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCuratorRolloutStatus.
func (in *ClusterCuratorRolloutStatus) DeepCopy() *ClusterCuratorRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCuratorRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencySpec) DeepCopyInto(out *ConcurrencySpec) {
	*out = *in
	if in.SoakDuration != nil {
		in, out := &in.SoakDuration, &out.SoakDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencySpec.
func (in *ConcurrencySpec) DeepCopy() *ConcurrencySpec {
	if in == nil {
		return nil
	}
	out := new(ConcurrencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedClusterInfo) DeepCopyInto(out *FailedClusterInfo) {
	*out = *in
	if in.FailedAt != nil {
		in, out := &in.FailedAt, &out.FailedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedClusterInfo.
func (in *FailedClusterInfo) DeepCopy() *FailedClusterInfo {
	if in == nil {
		return nil
	}
	out := new(FailedClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InProgressClusterInfo) DeepCopyInto(out *InProgressClusterInfo) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InProgressClusterInfo.
func (in *InProgressClusterInfo) DeepCopy() *InProgressClusterInfo {
	if in == nil {
		return nil
	}
	out := new(InProgressClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementReference) DeepCopyInto(out *PlacementReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementReference.
func (in *PlacementReference) DeepCopy() *PlacementReference {
	if in == nil {
		return nil
	}
	out := new(PlacementReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementStatus) DeepCopyInto(out *PlacementStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementStatus.
func (in *PlacementStatus) DeepCopy() *PlacementStatus {
	if in == nil {
		return nil
	}
	out := new(PlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStep) DeepCopyInto(out *RolloutStep) {
	*out = *in
	out.Counts = in.Counts
	if in.SoakDuration != nil {
		in, out := &in.SoakDuration, &out.SoakDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(ConcurrencySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BatchClusters != nil {
		in, out := &in.BatchClusters, &out.BatchClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BatchSoakEndsAt != nil {
		in, out := &in.BatchSoakEndsAt, &out.BatchSoakEndsAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.SoakEndsAt != nil {
		in, out := &in.SoakEndsAt, &out.SoakEndsAt
		*out = (*in).DeepCopy()
	}
	if in.FailedClusters != nil {
		in, out := &in.FailedClusters, &out.FailedClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStep.
func (in *RolloutStep) DeepCopy() *RolloutStep {
	if in == nil {
		return nil
	}
	out := new(RolloutStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectionSpec) DeepCopyInto(out *SelectionSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementRef != nil {
		in, out := &in.PlacementRef, &out.PlacementRef
		*out = new(PlacementReference)
		**out = **in
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(ConcurrencySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SoakDuration != nil {
		in, out := &in.SoakDuration, &out.SoakDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]SelectionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectionSpec.
func (in *SelectionSpec) DeepCopy() *SelectionSpec {
	if in == nil {
		return nil
	}
	out := new(SelectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoakStatus) DeepCopyInto(out *SoakStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.EndsAt != nil {
		in, out := &in.EndsAt, &out.EndsAt
		*out = (*in).DeepCopy()
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoakStatus.
func (in *SoakStatus) DeepCopy() *SoakStatus {
	if in == nil {
		return nil
	}
	out := new(SoakStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateCounts) DeepCopyInto(out *StateCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateCounts.
func (in *StateCounts) DeepCopy() *StateCounts {
	if in == nil {
		return nil
	}
	out := new(StateCounts)
	in.DeepCopyInto(out)
	return out
}
